name: Meterian vulnerability scan workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Scan project with the Meterian client
            uses: MeterianHQ/meterian-github-action@v1.0.16
            env:
                METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
            with:
                cli_args: "" #[ Meterian CLI Options ]
